name: Deploy to Production
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage --watchAll=false

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files

      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here
          # For example, you can use rsync or scp to transfer files to the server
          # rsync -avz --delete ./build/ user@your-server:/path/to/production
          # or
          # scp -r ./build/* user@your-server:/path/to/production
          echo "Deployment complete."

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send notification
        run: |
          echo "Sending notification..."
          # Add your notification commands here
          # For example, you can use curl to send a message to a Slack channel
          # curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment to production complete!"}' https://hooks.slack.com/services/your/slack/webhook
          echo "Notification sent."

  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start development server
        run: npm run dev